QUESTIONS_META = {
    "Q1": "Which category best describes you?",
    "Q2": "What is your primary role in the credential verification process?",
    "Q3": "How frequently do you deal with educational or professional credential verification?",
    "Q4": "How are educational/professional credentials usually submitted or verified in your experience?",
    "Q5": "How long does credential verification typically take?",
    "Q6": "Have you experienced delays because of manual credential verification?",
    "Q7": "If yes, what were the main reasons for the delay?",
    "Q8": "How comfortable are you with sharing complete educational or identity documents online?",
    "Q9": "What concerns do you have when sharing complete credentials online?",
    "Q10": "How concerned are you about identity theft or misuse of personal information from uploaded credentials?",
    "Q11": "Have you ever submitted the same educational/identity documents to multiple organizations or online platforms?",
    "Q12": "Do you know what happens to your documents after submitting them to an organization or online platform?",
    "Q13": "How easy do you think it is to digitally manipulate or forge an educational certificate?",
    "Q14": "Have you ever encountered or suspected a forged, manipulated, or invalid certificate?",
    "Q15": "How confident are you that a visually presented digital certificate is genuine?",
    "Q16": "What methods do you currently use to determine whether a credential is genuine?",
    "Q17": "How would you rate the current credential verification process?",
    "Q18": "Which problems do you experience with the current system?",
    "Q19": "Which ONE problem is the most serious?",
    "Q20": "How useful would a system like CredenSync be for you?",
    "Q21": "Would you prefer to prove a qualification without sharing the complete certificate/document?",
    "Q22": "How valuable would it be to verify a qualification without revealing other personal information contained in the certificate?",
    "Q23": "Which information would you prefer to prove without revealing the complete document?",
    "Q24": "Would you trust a credential verification system that combines AI-based authenticity checking, blockchain records, and Zero-Knowledge Proofs?",
    "Q25": "Would you use a system like CredenSync if it were available?",
    "Q26": "Would you recommend such a system to others?",
    "Q27": "What would prevent you from using CredenSync?",
    "Q28": "What would make you trust such a system?",
    "Q29": "What is the biggest problem you face with the current credential verification process?",
    "Q30": "Can you describe a situation where credential verification caused a delay, inconvenience, or difficulty?",
    "Q31": "What concerns you most when submitting educational or identity documents online?",
    "Q32": "In your opinion, how can credential verification be made more secure and privacy-friendly?",
    "Q33": "What features would you expect from an ideal digital credential verification system?",
    "Q34": "Do you have any suggestions or concerns regarding the CredenSync concept?",
    "Q35": "Would you be willing to participate in a follow-up interview or product testing session?",
    "Q36": "Optional follow-up contact information"
}
